config/routes.rb
ShopApp::Application.routes.draw do
 

 

  scope '/admin' do
  devise_for :users
end

  namespace :admin do
    root :to => 'admin#index'
    resources :orders
    resources :categories
    resources :products
   end 
  match "/categories/:id" => "categories#show"
  match 'cart' => "order#index"
  match 'cart/add/:id' => "order#add"
  match 'cart/delete/:id' => "order#delete"
  match 'cart/checkout' => "order#checkout"
  
  match 'search/results' => "search#results"
  
  resource :shop 
  resource :order
  resources :products
  resources :categories 
  resources :order_items

 
  root :to => 'shop#index'
end

app/models/buyer.rb
class Buyer< ActiveRecord::Base
	attr_accessible :first_name,:last_name
	has_many :orders
end

app/models/category.rb
class Category< ActiveRecord::Base
	attr_accessible :name
	has_many :products
end

app/models/order.rb
class Order< ActiveRecord::Base
	attr_accessible :buyer_id,:confirmed
	belongs_to :buyer
	has_many :order_items
end

app/models/order_item.rb
class OrderItem< ActiveRecord::Base
	attr_accessible :order_id,:product_id,:quantity
	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category	
	attr_accessible :name, :description, :price,:category_id	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
	before_filter :authenticate_user!
	layout "admin"

	def index
	end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController


  def index
    @categories = Category.all
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])

    @category.save
    redirect_to :back
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to :back
    
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController


  def index
    @orders = Order.where(:confirmed => 'true')
  end

  
  def destroy
    @orders = Order.find(params[:id])
    @orders.destroy

    redirect_to :back
    
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.create({:name => "New product", :description => "", :price => 0})
    redirect_to edit_admin_product_path(@product)
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
  end

  def create
    @product = Product.new(params[:product])

    if @product.save
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(params[:product])
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    
    redirect_to :back
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :initialize_current_buyer
  
  def initialize_current_buyer
  	@current_buyer ||= session[:buyer_id] && Buyer.find(session[:buyer_id])
  	if @current_buyer == nil
  		@current_buyer = Buyer.create
  		session[:buyer_id] = @current_buyer.id
  	end
    @current_cart = @current_buyer.orders.where(:confirmed => 'false').first
    if @current_cart == nil
  		@current_cart = Order.create(:buyer_id => @current_buyer.id,:confirmed => 'false')
  	end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show 
		@category = Category.find(params[:id])
	end
  end

app/controllers/order_controller.rb
class OrderController < ApplicationController
	def add 
		@product = Product.find(params[:id])
		@order_item = OrderItem.where(:product_id => @product.id, :order_id => @current_cart.id).first
		if @order_item == nil
		@order_item = OrderItem.create(:product_id => @product.id, :order_id => @current_cart.id,:quantity => 1)
		else
		@order_item.quantity += 1
		@order_item.save
		end 
		redirect_to :back
	end

	def delete
		@orderitem = OrderItem.find(params[:id])
		@orderitem.destroy
		redirect_to :back
	end

	def checkout
    @order = Order.find(@current_cart.id)
	if @order.order_items.empty?
      flash[:notice] = 'Empty cart'
      redirect_to :back
    else
    @order.confirmed = true
    @order.save
    @current_cart = Order.create(:buyer_id => @current_buyer.id,:confirmed => 'false')
    redirect_to :back
    end
  end
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def show
		@product = Product.find(params[:id])
	end
  end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def results
    @categories = Category.all
    @query = params[:q].clone 
    @q = Product.search(@query)
    @result = @q.result
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
	def index
		@categories = Category.all
		@products = Product.all
	end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admin/index.html.erb
<h1>Admin panel</h1>

app/views/admin/categories/edit.html.erb
<h1>Edit category</h1>

<%= form_for(@category, :url => admin_category_path(@category)) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to '< Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>List of categories</h1>

<table>
  <tr>
    <th>Name<th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
    <td><%= link_to 'Delete', admin_category_path(category), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<h2>Add category</h2>

<%= form_for(Category.new, :url => admin_categories_path) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/orders/index.html.erb
<h1>List of orders</h1>

<table>
  <tr>
    <th>Order Id</th>
    <th>Buyer Id</th>
    <th>Products</th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.id %></td>
    <td><%= order.buyer.id %></td>
    <td>
    <% order.order_items.each do |order_item| %>
 <%= order_item.product.name %>
<%= order_item.quantity %> <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/admin/products/edit.html.erb
<h1>Edit of products</h1>

<%= form_for(@product, :url => admin_product_path(@product)) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= collection_select(:product, :category_id, @categories, :id, :name, {:prompt => false }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>




<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>List of products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td><%= product.category.name %></td>
    <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
    <td><%= link_to 'Delete', admin_product_path(product), confirm: 'Are you sure ?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add product', new_admin_product_path %>

app/views/categories/show.html.erb
<%= render :partial => 'layouts/header' %>

<h1><%= @category.name%></h1>

<h1>List of Products</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th></th>
    <th></th>
  </tr>
 
<% @category.products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td><%= link_to 'Show', product %></td>
    <td>
    <%= form_tag :controller => :order, :action => :add, :id => product do %>
      <%= submit_tag 'Add to cart' %>
    <% end %>
    </td>
  </tr>
<% end %> 
</table>
 
<br />

app/views/layouts/_header.html.erb
<div id="head_bar">
<div class="wrap">
<div class="search">
    Search: <%= search_form_for Product.search(params[:q]), :url=>search_results_path do |f| %>
      <%= f.label( :name_cont, "Name") %>
      <%= f.text_field :name_cont %>
      <br />
      <%= f.label( :description_cont, "Description") %>
      <%= f.text_field :description_cont %>
      <br />
      <%= f.label( :price_gteq, "Price from :") %>
      <%= f.text_field :price_gteq , :style => 'width:70px;' %>
      <%= f.label( :price_lteq, "Price to :") %>
      <%= f.text_field :price_lteq, :style => 'width:70px;' %>
      <br />
      <%= f.submit "Search" %>
    <% end %>
</div>
<div class="basket">Basket</div>
<table>
  <tr>
    <th>Title</th>
    <th>Quantity</th>
    <th></th>
  </tr>
<% @current_cart.order_items.each do |order_item| %>
  <tr>
    <td><%= order_item.product.name %></td>
    <td><%= order_item.quantity %></td>
    <td><%= form_tag :controller => :order, :action => :delete, :id => order_item  do %>
      <%= submit_tag 'Delete' %>
    <% end %>
    </td>
  </tr>
<% end %>
<tr>
  	<td><%= form_tag :controller => :order, :action => :checkout do %>
      <%= submit_tag 'Checkout' %>
    <% end %>
  </tr> 
</table> 
</div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding: 20px;">

<%= link_to 'Orders', admin_orders_path %> |
<%= link_to 'Categories', admin_categories_path %> |
<%= link_to 'Products', admin_products_path %>
<br />
<hr />

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>



<div class="wrap">
<%= yield %>
</div>

</body>
</html>

app/views/products/edit.html.erb
<h1>Edit of products</h1>

<%= form_for(@product, :url => admin_product_path(@product)) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= collection_select(:product, :category_id, @categories, :id, :name, {:prompt => false }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', admin_products_path %>

app/views/products/show.html.erb
<%= render :partial => 'layouts/header' %>

<h1><%= @product.name%></h1>

<table>

  <tr>
    <td> Description : <%= @product.description %></td>
    <td>Price : <%= @product.price %></td>
    <td>
    <%= form_tag :controller => :order, :action => :add, :id => @product do %>
      <%= submit_tag 'Add to cart' %>
    <% end %>
    </td>
  </tr>
</table>
 
<br />

app/views/search/results.html.erb
  <h3>Search Result</h3>
 
    <% @result.each do |t| %>
      <p><%= link_to t.name, t %></p>
    <% end %>

app/views/shop/index.html.erb
<%= render :partial => 'layouts/header' %>

<h1>List of Categories</h1>

<table>
  
 
 
<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
  </tr>
<% end %>	
</table>



<h1>List of Products</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Category</th>.
    <th></th>
    <th></th>
  </tr>
 
<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td><%= product.category.name %></td>
    <td><%= link_to 'Show', product %></td>
     <td>
    <%= form_tag :controller => :order, :action => :add, :id => product do %>
      <%= submit_tag 'Add to cart' %>
    <% end %>
    </td>
  </tr>
<% end %>	
</table>
 
<br />